#explained here : https://www.youtube.com/watch?v=XH9XgiVM_z4&t=1435s&ab_channel=Jim%27sGarage
# be sure to create the proxy network before creating the container
# sudo docker network create proxy

# additions frmo this https://www.youtube.com/watch?v=IBlZgrwc1T8&t=280s&ab_channel=Jim%27sGarage
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
 
    ports:
      - 80:80
      - 81:81  #for external facing apps
      - 443:443
      - 444:444  #for external facing apps
      - 8080:8080 #for the dashboard
    environment:
      - CF_API_EMAIL=mdorahy@gmail.com
  # old    - CF_DNS_API_TOKEN=02B0mWuNhRmaEXET2kVh7VvVAJtehl9VV_8ZPu7Q
      - CF_DNS_API_TOKEN=oRxU49-GM2-lAhYRYyzH-6D9c3dY56AjupAR6ZsR

  # all errrs and debugging in ~/data/traefik/logs/traefik.log  <<<<-------------*****

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/matt/data/traefik/traefik.yml:/traefik.yml:ro
      - /home/matt/data/traefik/acme.json:/acme.json
      - /home/matt/data/traefik/config.yml:/config.yml:ro
      - /home/matt/data/traefik/logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik-dashboard.mpengor.com`)"
 #next line uses the encoded password that is created using: echo $(htpasswd -nb "admin" "<unencodedpassword>") | sed -e s/\\$/\\$\\$/g
# this will generate an encoded password that is shown below ($$....). When logging into the traffic dashboard, use admin/unencodedpassword
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$Cbm9JAJX$$YeiSAnaZKE.Fo.GcLJ0gN."
      #nxet 3 line automatic redirecton from http to https
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
     # routes into the proxy/traefik
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.mpengor.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
   #use cloudflare to generate certs
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
   #i want cloudflare the generate certs for these two domains
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=mpengor.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.mpengor.com"
   #enable API so traefik logs can be accessed by grafana and prometheus etc
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    name: proxy
    external: true

